export const authConstants = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",
}

export const signupConstants = {
    SIGNUP_REQUEST: "SIGNUP_REQUEST",
    SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
    SIGNUP_FAILURE: "SIGNUP_FAILURE"
}

export const newsletterConstants = {
    NEWSLETTER_REQUEST: "NEWSLETTER_REQUEST",
    NEWSLETTER_SUCCESS: "NEWSLETTER_SUCCESS",
    NEWSLETTER_FAILURE: "NEWSLETTER_FAILURE"
}

export const queryConstants = {
    QUERY_REQUEST: "QUERY_REQUEST",
    QUERY_SUCCESS: "QUERY_SUCCESS",
    QUERY_FAILURE: "QUERY_FAILURE"
}

export const quoteConstants = {
    QUOTE_REQUEST: "QUOTE_REQUEST",
    QUOTE_SUCCESS: "QUOTE_SUCCESS",
    QUOTE_FAILURE: "QUOTE_FAILURE"
}

export const userConstants = {
    FOLLOW_USER_REQUEST: "FOLLOW_USER_REQUEST",
    FOLLOW_USER_SUCCESS: "FOLLOW_USER_SUCCESS",
    FOLLOW_USER_FAILURE: "FOLLOW_USER_FAILURE",
}

export const blogConstants = {
    GET_ALL_BLOGS_REQUEST: "GET_ALL_BLOGS_REQUEST",
    GET_ALL_BLOGS_SUCCESS: "GET_ALL_BLOGS_SUCCESS",
    GET_ALL_BLOGS_FAILURE: "GET_ALL_BLOGS_FAILURE",
    GET_A_BLOG_REQUEST: "GET_A_BLOG_REQUEST",
    GET_A_BLOG_SUCCESS: "GET_A_BLOG_SUCCESS",
    GET_A_BLOG_FAILURE: "GET_A_BLOG_FAILURE",
    GET_BLOG_BY_CATEGORY_REQUEST: "GET_BLOG_BY_CATEGORY_REQUEST",
    GET_BLOG_BY_CATEGORY_SUCCESS: "GET_BLOG_BY_CATEGORY_SUCCESS",
    GET_BLOG_BY_CATEGORY_FAILURE: "GET_BLOG_BY_CATEGORY_FAILURE",
    GET_BLOG_USER_REQUEST: "GET_BLOG_USER_REQUEST",
    GET_BLOG_USER_SUCCESS: "GET_BLOG_USER_SUCCESS",
    GET_BLOG_USER_FAILURE: "GET_BLOG_USER_FAILURE",
    COMMENT_REQUEST: "COMMENT_REQUEST",
    COMMENT_SUCCESS: "COMMENT_SUCCESS",
    COMMENT_FAILURE: "COMMENT_FAILURE",
    GET_ALL_CATEGORY_REQUEST: "GET_ALL_CATEGORY_REQUEST",
    GET_ALL_CATEGORY_SUCCESS: "GET_ALL_CATEGORY_SUCCESS",
    GET_ALL_CATEGORY_FAILURE: "GET_ALL_CATEGORY_FAILURE"
}